### ISSUE TITLE
Set up continuous integration

### ISSUE THREAD

**Issue by afeld** [18F/dns#12]
Would be great to have pull requests tested with [`terraform validate`](https://www.terraform.io/docs/commands/validate.html) so we know we don't have syntax errors, etc. 

/cc @LinuxBozo

**Comment by afeld** [comment]
@jezhumble Would you prefer such a thing be done in [GoCD](https://www.go.cd/)? Otherwise, I can take a crack at setting it up in Travis.

**Comment by jezhumble** [comment]
Hi! The GoCD instance isn't designed to be public, so I think Travis is fine.
