### ISSUE TITLE
Create toaster.18f.gov

### ISSUE THREAD

**Issue by amoose** [18F/dns#136]
We've rebranded Fugacious to Toaster and would prefer to host at toaster.18f.gov

Please use the same configuration as fugacious.18f.gov, which appears to be two CNAME entries:

```
;; QUESTION SECTION:
;fugacious.18f.gov.		IN	A

;; ANSWER SECTION:
fugacious.18f.gov.	299	IN	CNAME	dualstack.production-star-18f-gov-elb-1963420885.us-gov-west-1.elb.amazonaws.com.
dualstack.production-star-18f-gov-elb-1963420885.us-gov-west-1.elb.amazonaws.com. 60 IN	A 52.222.35.187
dualstack.production-star-18f-gov-elb-1963420885.us-gov-west-1.elb.amazonaws.com. 60 IN	A 96.127.47.199
```

Question: can cloud.gov handle the redirects from fugacious -> toaster? If it's a pain, I can configure at the app level.

**Comment by afeld** [comment]
@amoose Game to send a pull request? Instructions are [here](https://github.com/18F/dns#making-changes).

> can cloud.gov handle the redirects from fugacious -> toaster?

Not cloud.gov directly. If you don't want to [have Rack/Rails redirect to the canonical hostname](https://github.com/tylerhunt/rack-canonical-host), you can [set up a little redirector app](https://cloud.gov/docs/apps/static/#redirect-all-traffic).

**Comment by amoose** [comment]
Thanks, Aidan. I guess this probably isn't needed, after all. It looks like we're sunsetting Fugacious before the end of the fiscal year.
