### ISSUE TITLE
add more details about where the pieces live

### ISSUE THREAD

**Issue by afeld** [18F/dns#147]
From @brittag:

> This needs more detail about the role of gsa-tts-domains, how the [DNS lives inside the cloud.gov AWS account](https://docs.google.com/document/d/110o1L7EOby3hvE5d-cDhg2LBLHymbZLnMPe9kuk4qp8/edit), etc.

**Comment by brittag** [comment]
Thanks Aidan! For context, `gsa-tts-domains` is an org on cloud.gov.

**Comment by alain-hoang** [comment]
Thank you for providing context on `gsa-tts-domains`.  In trying to query the org I am seeing a finding error message so cannot provide anymore clarification regarding this org besides a member of the group `infrastructure-staff` cannot view it.  I've updated the wiki DNS page to include `how the DNS lives inside the cloud.gov AWS account`.  Could an appropriate member in `gsa-tts-domains` update with the desired clarifications?

**Comment by brittag** [comment]
Where is the wiki DNS page? The only Org Managers on `gsa-tts-domains` are @jmcarp and @LinuxBozo - I suspect that needs to be changed to Infra members instead of cloud.gov team members (which is part of why I brought up this issues).

**Comment by alain-hoang** [comment]
@brittag The wiki page is located [here](https://github.com/18F/Infrastructure/wiki/DNS-architecture).   I don't have further insight on Infrastructure involvement as Org managers for `gsa-tts-domains`.  That discussion would be better answered by Kimber

**Comment by brittag** [comment]
Thanks! I recommend linking that wiki page from the README in this repo. cc @kimberbat for next steps on getting `gsa-tts-domains` integrated into Infra processes/docs correctly.

**Comment by alain-hoang** [comment]
Created a [PR](https://github.com/18F/dns/pull/148) for linking the wiki page in the README.  After it passes a review, it should be ready to go.

**Comment by alain-hoang** [comment]
After getting some clarification, it appears that the `gsa-tts-domains` doesn't  fall under Infrastructure at this time.  Need more clarification on where ownership lies (helpdesk might be able to confirm?)

**Comment by brittag** [comment]
Which helpdesk do you mean?

**Comment by afeld** [comment]
Closing this out, as the wiki page is now linked to.
