### ISSUE TITLE
Automated the checking of unused DNS records

### ISSUE THREAD

**Issue by afeld** [18F/dns#176]
We should clean out records from this repository that aren't actually in use. Some ideas of things to check for:

* Public Route 53 zones where the domain isn't actually pointing to those nameservers
* `A`, `AAAA`, and `CNAME` records where that hostname doesn't respond

We should add a script to the repository to check for these things.

**Comment by adunkman** [comment]
Noticed [continua11y.18f.gov](https://continua11y.18f.gov/) is a 404 today: https://github.com/18F/dns/blob/cb9c678b51bbd4a88e79e071f9dbb4399ec0522b/terraform/18f.gov.tf#L395-L401

**Comment by lauraGgit** [comment]
@stvnrlly i believe that this was one of your projects - would you say that this makes sense to take out?

**Comment by afeld** [comment]
Closing as stale.
