### ISSUE TITLE
ensure all records in new AWS account are managed by Terraform

### ISSUE THREAD

**Issue by afeld** [18F/dns#180]
Looked like there were some already in there before we deployed the ones from this repository.

**Comment by afeld** [comment]
@erik-burgess Mind dropping the list of Hosted Zones from Route 53 here, for reference?

**Comment by erik-burgess** [comment]
Migrated delegated domains into TTS DNS process. The migrated domains were:  

sbst.gov
calc.gsa.gov
open.fec.gov
beta.fec.gov
collegescorecard.ed.gov
analytics.usa.gov
gsaforecast.gsa.gov
open.foia.gov
pulse.cio.gov
https.cio.gov
discovery.gsa.gov
cld.epa.gov
