### ISSUE TITLE
As a 18F staff member, I want to know how to use this repository

### ISSUE THREAD

**Issue by afeld** [18F/dns#2]
A README with a description and instructions (as well as our [boilerplate files](https://github.com/18F/open-source-policy/blob/master/practice.md#how-to-license-18f-repos)) would be great!

**Comment by jezhumble** [comment]
Thanks, I'll get on it. On the boilerplate files, contributions probably isn't appropriate (I can't see a scenario where we'd welcome changes to our DNS configuration from outside of 18F)

**Comment by afeld** [comment]
Understood. We should include the license at the very least.

**Comment by afeld** [comment]
Also, does the configuration in this repo get applied automatically, or does it need to be run by someone after every update?

**Comment by afeld** [comment]
Closed by https://github.com/18F/dns/commit/95a32c78cbec509742bb5b15200d972ec16cc3a2 and https://github.com/18F/dns/commit/c1fdc38771f3727cab81f48aee17417aa782523f.
