### ISSUE TITLE
How do I add a new domain on Federalist for a site where TTS owns the DNS?

### ISSUE THREAD

**Issue by wslack** [18F/dns#23]
I think the text to merge looks like one of the two options below. Questions:

1. Is it correct to say we always want the CNAME option?
2. If so, is the bolded text the only piece that would be changed?
3. If not, where does the "zone ID" come from when doing an A record?
4. Should Federalist have the power to merge its own PRs into this?

resource "aws_route53_record" "18f_gov_**sample-website-B_18f_gov**_cname" {
  zone_id = "${aws_route53_zone.18f_gov_zone.zone_id}"
  name = "**sample-website-A.18f.gov.**"
  type = "CNAME"
  ttl = 300
  records = ["**d1z8tmjf5ismhl.cloudfront.net.**"]
}

resource "aws_route53_record" "18f_gov_climate-data-user-study_18f_gov_a" {
  zone_id = "${aws_route53_zone.18f_gov_zone.zone_id}"
  name = "sample-website-B.18f.gov."
  type = "A"
  alias {
    name = "dgkam57c0xckv.cloudfront.net."
    zone_id = "Z2FDTNDATAQYW2"
    evaluate_target_health = false
  }
}

**Comment by wslack** [comment]
1. Answer is YES.

**Comment by wslack** [comment]
Which raises the point:

Are the settings correct for these sites:

- https://github.com/18F/dns/blob/deploy/terraform/18f.gov.tf#L321
- https://github.com/18F/dns/blob/deploy/terraform/18f.gov.tf#L426

**Comment by NoahKunin** [comment]
2. That's my understanding. Let's test it!
3. Zone ID is pulled via the Python scripting here via the API. Nothing in a `${}` should ever be hardcoded back in while using Terraform. That's the convention for a reference variable or [interpolation](https://www.terraform.io/docs/configuration/interpolation.html). [You can see the logic here](https://github.com/18F/dns/blob/deploy/get_zone.py).
4. Federalist should have the power to _accept_ PRs while still adhering to the two-person rule. So two Federalist engineering staff can accept a PR. 
5. Are the A records correct? AFAIK...the sites resolve, but I might not understand the question.

Pinging back to you @wslack, pong back if need be.

**Comment by wslack** [comment]
Thanks Noah!

5. I'm trying to understand why those records don't have CNAMEs.

**Comment by datn** [comment]
@wslack the A record is actually an alias, which is Route 53's own "super-CNAME" functionality. See [here](http://docs.aws.amazon.com/Route53/latest/DeveloperGuide/resource-record-sets-choosing-alias-non-alias.html) for more.

**Comment by wslack** [comment]
@datn should we use A instead of CNAME given that AWS charges for each CNAME?

**Comment by datn** [comment]
@wslack You have it backwards -- if I understand what I am reading in terraform correctly, we are currently using the thing they **don't** charge extra for, which is an A record and an alias.

**Comment by wslack** [comment]
Right - I mean, there are CNAMEs to cloudfront URLs all over this repo. I'm wondering if we should use A instead of CNAME (might be moot given fairly low traffic volume)

**Comment by datn** [comment]
Yes, Route 53's own A+alias functionality is preferable because it is native to Route 53 and AWS's network architecture. I think the charge is, so to speak, a way of discouraging bad and outdated habits from regular DNS. We should use their special powers where we can.

**Comment by afeld** [comment]
@wslack Still relevant?

**Comment by wslack** [comment]
yep, this is what I was looking for

**Comment by afeld** [comment]
https://federalist-docs.18f.gov/pages/how-federalist-works/custom-urls/

**Comment by wslack** [comment]
(issue still useful but doesn't need to be open)
