### ISSUE TITLE
The `master` branch on this repo should be deleted

### ISSUE THREAD

**Issue by wslack** [18F/dns#24]

**Comment by jmcarp** [comment]
Why not just stick with master? What's the purpose of the deploy branch?

**Comment by wslack** [comment]
@jmcarp AFAIK the deploy branch is the one that makes everything work (per the repo README). As such, having an additional branch called "master" just seems confusing.

**Comment by jmcarp** [comment]
Agreed that there should only be one branch, but why not use the default of master?

**Comment by wslack** [comment]
Per Slack convo, are you comfortable with me deleting the `master` branch @jmcarp?

**Comment by wslack** [comment]
Update: deleting per Slack convo.
