### ISSUE TITLE
Create DNS for stage.fec.gov

### ISSUE THREAD

**Issue by patphongs** [18F/dns#279]
@afeld we have a question about creating a new stage.fec.gov DNS within this repo. 

We want to enable cloudfront caching on our staging environment, in order to do this we need to set up a stage.fec.gov cdn-route. First off, would we need to submit a terraform PR to get name servers in order for our service provider to delegate a domain? 

Would the below code work in a new `/terraform/stage.fec.gov.tf`? This code would essentially output name servers for us to point to? See below:

```
# Setting up a staging domain in order to set up a new cdn-route
# to configuring caching headers in cloudfront

resource "aws_route53_zone" "stage_gov_us_zone" {
  name = "stage.fec.gov"
  tags {
    Project = "dns"
  }
}

output "stage_gov_us_ns" {
  value="${aws_route53_zone.stage_gov_us_zone.name_servers}"
}
```
Once we get the name servers and have it delegated, we should be able to take it from there to set cloudfront caching on our side via the cdn-route instructions in this section of the cloud.gov docs: https://cloud.gov/docs/services/cdn-route/#how-to-create-an-instance-of-this-service

cc @vrajmohan

**Comment by afeld** [comment]
Given that [we need to move the FEC records out of this repository/account](https://github.com/fecgov/fec-infrastructure/issues/55) anyway, setting up a new subdomain would be a great opportunity to try that out!

The example you provided looks good. Steps from here are:

1. Add that code above to [fec-infrastructure](https://github.com/fecgov/fec-infrastructure/tree/master/terraform), which will create nameservers for you.
1. Get the nameserver values that it outputs when deployed.
1. Take those nameserver values and ask the FEC IT folks to delegate `stage.fec.gov`.

Does that make sense?

**Comment by patphongs** [comment]
Thanks @afeld! Yes that makes sense to me. We just need to wait for the full AWS transfer to go through in order to maintain this ourselves. We saw your open [issue](https://github.com/fecgov/fec-infrastructure/issues/55) in our fec-infrastructure, and that is also waiting for the transfer to complete. Creating our own DNS and terraform configuration for the stage.fec.gov domain can wait until the transfer is complete, I hear it's super close. We'll most likely reach out to you again for some extra guidance and training on terraform once we're ready to move things along.

**Comment by afeld** [comment]
No longer relevant, I believe.

**Comment by jontours** [comment]
That is correct.
