### ISSUE TITLE
Standardize on TTL values

### ISSUE THREAD

**Issue by jgrevich** [18F/dns#291]
I noticed that we have a wide array of values used for TTL. I'm guessing that the majority of them can be increased to a larger value.

It's fairly common practice to only use short TTLs while testing out DNS changes and for failover setups. In other cases it is recommended that people use TTL values of 24 hours/86400s.

https://support.google.com/a/answer/48090#TTL
> Once the records are configured correctly, we recommend setting a TTL value of 86400, which tells servers across the Internet to check every 24 hours for updates to the record.

https://support.rackspace.com/how-to/about-ttl-best-practices/
> Generally, we recommend a TTL of 24 hours (86,400 seconds). However, if you are planning to make DNS changes, you should lower the TTL to 5 minutes (300 seconds) at least 24 hours in advance of making the changes. After the changes are made, increase the TTL back to 24 hours.

- [ ] determine suggested short/long term TTL values
- [ ] update all records accordingly

**Comment by afeld** [comment]
Closing as stale.

**Comment by jgrevich** [comment]
Shouldn't we do something about this? Seems like we should be following best practices here. Perhaps just not high priority?
