### ISSUE TITLE
resume use of docker image hashicorp/terraform:light ?

### ISSUE THREAD

**Issue by amirbey** [18F/dns#332]
hashicorp/terraform was recently release to version 0.12 which appears to have new validation rules and blocking updates to this 18f/dns.  For now, the docker image has been pinned to 0.11.4:
https://github.com/18F/dns/pull/331

A longterm solution is needed to resume use of hashicorp/terraform:light

**Comment by afeld** [comment]
Closing in favor of https://github.com/18F/dns/issues/411.
