### ISSUE TITLE
As the Technology Portfolio, we want DNS control over TTS domains

### ISSUE THREAD

**Issue by afeld** [18F/dns#351]
See about getting DNS delegation of the following:

- [ ] 18f.gsa.gov
- [ ] tts.gsa.gov
- [ ] data.gov
- [ ] fedramp.gov
- [ ] ~~login.gov~~

cc https://github.com/18F/tts-tech-portfolio/issues/23

**Comment by adborden** [comment]
@afeld just noticed this disclaimer in the [README](https://github.com/18f/dns#making-changes). Would that exclude data.gov (moderate impact)?

> Please note: only production systems with an ATO that are categorized as Low impact should have their DNS configuration here. If you wish to create DNS records for pre-production systems, please use the domain sandbox.gov which is available in the TTS Sandbox account.

**Comment by afeld** [comment]
Umm, that's a good question...not sure if that means we _can't_ put systems with other impact levels here. Want to reach out to your ISSO/ISSM, or should I ask...someone?

**Comment by afeld** [comment]
Note this is more about the domain registrations than where the name servers (DNS) are.

**Comment by afeld** [comment]
Sorry, correction: this _is_ about the DNS, not about the registrations.

**Comment by gbinal** [comment]
@afeld - Any thoughts on if any/which of these we’d also want to include in this effort as well?   I believe they represent everything we operate.

https://github.com/GSA/machine-readable-TTS/issues/1#issuecomment-534636322

I know that we’ve got a spreadsheet that has almost all of those represented but I think there’s a few more in there.

FWIW - I’m a big fan of dogfooding the TTS/DNS effort and am glad to help rally programs to help with this if useful.

**Comment by afeld** [comment]
All! ...minus the potential caveat of Moderate systems that @adborden raised above.

**Comment by afeld** [comment]
Closing as not a priority.
