### ISSUE TITLE
As a domain owner, I would like to be notified about PRs for my domain

### ISSUE THREAD

**Issue by jeremyzilar** [18F/dns#357]
As a domain owner, I would like to be notified about PRs for my domain's terraform file.

**This is more of a "nice to have" than a risk but here is what I would be looking for:**
- Is there a new product or service launching that we should know about (unlikely, but possible)
- Are old legacy records being modified?
- Is there a need for a 301 redirect in this change ?
- are the changes being rolled out in the right order?
- are the DNS configurations being clearly documented in the file
- Who is the owner begin this product/service

**Comment by JJediny** [comment]
@jeremyzilar this is a great write up around the communication workflow for team's domain ownership, but so far common sense/trust model with the set of GitHub reviewers has been sufficient mitigation against making changes from external or not-know-contributors. 

Certainly, teams should/could include a comment section with team contact information before their terraform content for reviewers help in notification; but its unlikely we can manage rolling out a policy like this anytime soon. So, for now, we're going to close the issue as the action item isn't defined and ref this in favor of https://github.com/18F/tts-tech-portfolio/issues/201

Feel free to reopen or create a new issue off of this.
