### ISSUE TITLE
DMARC External Destination Verification for new top level domains not owned by TTS

### ISSUE THREAD

**Issue by Jkrzy** [18F/dns#378]
We're leveraging TTS DNS for a partner engagement which includes a new top level domain. Initial configuration was rolled out in #362.

This included GSA DMARC reporting destinations common to the other domains configured in this repo:

- dmarcfailures@gsa.gov
- dmarcreports@gsa.gov

However, a corresponding change was never made at `gsa.gov` to verify and accept DMARC reports from the new domain in question. ref: https://tools.ietf.org/html/rfc7489#section-3.2

1. Should the GSA reporting destinations be included in this DMARC record? 
    - The domain in question is owned by HHS. 
    - We're expected to [transition away from TTS DNS by 11/22/19](https://github.com/18F/samhsa-prototype/issues/554)
2. If yes, and GSA should receive these DMARC reports. What steps are necessary to setup external destination verification w/ `gsa.gov` ? 
    - e.g. `findtreatment.gov._report._dmarc.gsa.gov.`
    - Related to #363

**Comment by afeld** [comment]
Still relevant?

**Comment by its-a-lisa** [comment]
@Jkrzy nudge on if this is still relevant

**Comment by Jkrzy** [comment]
Not needed for any current 18F projects but this question could come up again in the future.
