### ISSUE TITLE
Update zone file for digitalgov.gov ECAS SSL verification

### ISSUE THREAD

**Issue by cokafo** [18F/dns#400]
Please make the specified update below:

 _D670A36BBFD8C7415F5A5997E8DD36A6.digitalgov.gov.   IN  CNAME  289FD47634D927D0054C6123597F4F24.FF461CB01C73BC95FD87C0AE0955A9CC.5e2f421173150.comodoca.com.

**Comment by jeremyzilar** [comment]
@cokafo Can you describe what this record is for? And who is requesting it?
Adding this to our documentation.

**Comment by cokafo** [comment]
Its for SSL certificate verification and needs to be done asap

**Comment by cokafo** [comment]
I am requesting the change

**Comment by jeremyzilar** [comment]
@cokafo We do need to know which SSL cert this fixes. 
`digitalgov.gov` has security certs provided through Let's Encrypt.
The only one that doesn't is the special one for DAP. (@tdlowden @JJediny )

If anything, we need to document what SSL cert this is for.

**Comment by cokafo** [comment]
It is  for a wildcard cert that will be used in the AWS ECAS platform for digitalgov.gov

**Comment by cokafo** [comment]
I recommend you talk with your manager if you have further questions.

**Comment by jeremyzilar** [comment]
@cokafo Can you tell us more about who requested the AWS ECAS platform?
