### ISSUE TITLE
upgrade to Terraform 0.12+

### ISSUE THREAD

**Issue by afeld** [18F/dns#411]
The major issue for all the 18f.us/18f.gov resources:

> In Terraform 0.12, resource names must start with a letter.

## Implementation Steps

- [x] Schedule time for migration with @amirbey 

## Acceptance Criterea

- [x] Terraform 14 plan / apply runs with no warnings or errors presented

**Comment by afeld** [comment]
A couple of Python scripts I had come up with to do similar migrations (renaming a bunch of resources in a consistent way):

- https://github.com/18F/tts-tech-portfolio/pull/618#issuecomment-658201956
- https://github.com/18F/tts-tech-portfolio/pull/428#issue-403883560

In case they're helpful!

**Comment by JJediny** [comment]
Complete 🎉 https://github.com/18F/dns/pull/513
