### ISSUE TITLE
Move Usability.gov domain to TTS 

### ISSUE THREAD

**Issue by jeremyzilar** [18F/dns#420]
We are preparing to move [Usability.gov](http://usability.gov/) from HHS to the GSA.

> ## Usability.gov will have a new home in 2020
> This long-standing UX resource will be part of the family of guidance offered by Digital.gov as part of Digital.gov’s mission to transform how government learns, builds, delivers, and measures digital services in the 21st century. [Read more](https://docs.google.com/document/d/1cv5l2pOOnJ6EDRU5AWfH93V-wx4yakQZuShaGT5clqo/edit) 

- Our REPO: https://github.com/GSA/digitalgov-usability
- Federalist Preview: https://cg-ca533af2-85d8-48d5-b022-a488db3d069b.app.cloud.gov/site/gsa/digitalgov-usability/

---

**The following is a list of things the things we are working on to make this transition possible.** We are looping in the TTS Infra team on this for visibility and additional guidance on making this a smooth transition.

_(feel free to edit/add as you see fit)_

### Approvals
- [x] Get the [domain transfer letter](https://docs.google.com/document/d/1YspX7XZklOVidmRhAXDnxYn1ahWOss0EO0q0qzLxrH8/edit) signed by Dave Shive
- [x] Coordinate with HHS on submitting the letters to DotGov.gov to get the transfer moving (_in progress_)

### Prepare Domain Transfer
Here is how I think the transfer will likely go
- [x] Get the Federalist site reviewed by the Federalist Team (in-progress)
- [x] Prepare the DNS records in a draft PR in the TTS DNS repo (see https://github.com/18F/dns/pull/422)
- [x] Ensure Sara Cope can manage the DotGov registry for this domain

### Make the Domain Transfer
- [x]  Coordinate with the Federalist team and TTS Infra team on a day to launch
- [x]  Alert the HHS IT team of the day we plan on making the switch
- [x]  Ask the Federalist team for Cloudfront URLs (_needs to be done within 12hrs of the launch_)
- [x]  Insert them into the [draft PR](https://github.com/18F/dns/pull/422) we created for this domain (see https://github.com/18F/dns/pull/422)
- [x]  Get the PR reviewed
- [x]  Make the switch in DotGov
- [x]  Merge the PR
- [ ]  Turn things on and off a few times till it works. 😆 
- [ ] [... unknown...]

**Comment by afeld** [comment]
Looks good!

> Coordinate with HHS IT team on switching the settings in the DotGov to point to GSA

Once the domain registration ownership gets transferred, we can change the nameservers ourselves, so I wouldn't bother asking HHS to do it.

**Comment by jeremyzilar** [comment]
Ok, the letter is signed by the GSA CIO, and we've sent it off to HHS so that they can creat their own letter.

**Comment by saracope** [comment]
Heads up that we're going to start working this transfer today and plan to have full cutover tomorrow.

**Comment by saracope** [comment]
@afeld Do we need to do anything for hsts preload?

**Comment by afeld** [comment]
It's [in the preload list](https://hstspreload.org/?domain=usability.gov). Federalist (or the cloud.gov CDN broker for the domain) seems to be setting the `strict-transport-security` header for other sites:

```
$ curl -Is https://handbook.tts.gsa.gov | grep -i transport
strict-transport-security: max-age=31536000; preload
```

It doesn't have the `includeSubDomains`, but seems that isn't one of the [Continued Requirements](https://hstspreload.org/?domain=usability.gov#continued-requirements). All set, I think!

**Comment by afeld** [comment]
I think we are all set! @saracope good to close?

**Comment by saracope** [comment]
Thanks!
