### ISSUE TITLE
automatically check for HSTS

### ISSUE THREAD

**Issue by afeld** [18F/dns#476]
## Background information

We want all of our domains to be [preloaded with HTTP Strict Transport Security (HSTS)](https://hstspreload.org/). We can add automated tests to ensure it's in place.

## Acceptance criteria

- An error is thrown (on a recurring basis) if a domain in this repository doesn't have the HSTS headers or isn't on the preload list

---

The assignee can add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by afeld** [comment]
From Sue Frederick:

> the Federalist ISSO will still have to manually check it in order to complete the Federalist Site Review form and process

**Comment by pburkholder** [comment]
FWIW, [here's an example of cloud.gov testing our HSTS](https://github.com/cloud-gov/cg-compliance/blob/master/audit/SC/controls/sc20.rb), but I don't yet test whether we're on the preload list, which I guess I could do with `GET https://hstspreload.com/api/v1/status/cloud.gov`

**Comment by afeld** [comment]
Since GSA already does these checks (if we remember correctly), this would be redundant. Closing in favor of https://github.com/18F/newrelic-terraform/issues/18.
