### ISSUE TITLE
Redirect USWDS components subdomain

### ISSUE THREAD

**Issue by afeijoo** [18F/dns#482]
We are deprecating https://components.designsystem.digital.gov. 

Can you please set up a 301 redirect from `components.designsystem.digital.gov` to `designsystem.digital.gov/components`?

Ammie

**Comment by afeijoo** [comment]
@afeld Decommissioning this public subdomain is a USWDS priority per GSA's web modernization efforts. It is not a full decommission, so I'm hoping it is a DNS task only.

**Comment by afeld** [comment]
We use a subset of the same template. "Decommissioning" is a spectrum 🌈

**Comment by amirbey** [comment]
Done 
https://github.com/18F/pages-redirects/pull/170
https://github.com/18F/dns/pull/495
