### ISSUE TITLE
Update plainlanguage.gov 

### ISSUE THREAD

**Issue by saracope** [18F/dns#484]
Follow-up to #477 

https://cloud.gov/docs/services/external-domain-service/#how-to-create-an-instance-of-this-service
- add an acme_challenge CNAME record as described in step 1
- add an Alias record for plainlanguage.gov will need to be as described in step 2

**Comment by amirbey** [comment]
resolved in:
https://github.com/18F/dns/pull/491
https://github.com/18F/dns/pull/486/files
