### ISSUE TITLE
Errors caused by using the new cloud.gov external domain service documentation 

### ISSUE THREAD

**Issue by JJediny** [18F/dns#493]
Using the Alias record and Zone id as documented in the cloud.gov documentation does not work when setting up a new redirect - https://cloud.gov/docs/services/external-domain-service/ cc @apburnes 

To setup a redirect we still need the full cloudfront url as the `alias_name` - see build failures from https://github.com/18F/dns/pull/491 for ref

**Comment by afeld** [comment]
cloud.gov is working on this.

**Comment by afeld** [comment]
Closing in favor of https://github.com/cloud-gov/cg-site/issues/1820.
