### ISSUE TITLE
Redirect portfolios.18f.gov to 18f.gsa.gov

### ISSUE THREAD

**Issue by jstrothman** [18F/dns#599]
18F no longer has portfolios and the repo for the site has been archived.
We'd like to redirect the subdomain to the 18F website.

## This issue is done when

- [ ] https://portfolios.18f.gov resolves to https://18f.gsa.gov

**Comment by adunkman** [comment]
[Completed](https://gsa-tts.slack.com/archives/C1NUUGTT5/p1660770908707369?thread_ts=1660008974.564219&cid=C1NUUGTT5)!

**Comment by jstrothman** [comment]
Thank you @adunkman !!!!!
