### ISSUE TITLE
Improve linting for DNS Concourse job

### ISSUE THREAD

**Issue by datn** [18F/dns#69]
Yoz's addition to the vote.gov DNS failed with the following error:

`* aws_route53_record.vote_gov_www_vote_gov_a: provider.aws: aws_route53_record: www.vote.gov: "ttl": required field is not set`

That should get checked in the PR stage.

**Comment by afeld** [comment]
Sounds like a good issue/pull request for `terraform validate`.

**Comment by datn** [comment]
Indeed @afeld , although I note that in this DNS repo, we don't have a CI testing step at all. @alain-hoang also notes that https://github.com/wata727/tflint exists for supposedly even finer linting.

**Comment by afeld** [comment]
@datn We do it through Travis rather than Concourse: https://github.com/18F/dns/blob/deploy/.travis.yml

**Comment by datn** [comment]
@afeld Thanks! I knew we used Travis generally, and I sure missed the `.travis.yml` file, but most importantly to this issue, I didn't see the testing happening in the first place.  Shouldn't I see a step where Travis is validating changes in PRs like this?: https://github.com/18F/dns/pull/62

**Comment by afeld** [comment]
> Shouldn't I see a step where Travis is validating changes in PRs like this?

<img width="791" alt="screen_shot_2017-03-10_at_4_28_19_pm" src="https://cloud.githubusercontent.com/assets/86842/23813854/c18ee64a-05ae-11e7-86bf-f0a1f042a2a6.png">

Is that what you mean?

**Comment by datn** [comment]
D'oh! Sorry about that, I completely missed those checks. In my (lame) defense, I was expecting it to look like this: 

<img width="600" alt="screen shot 2017-03-10 at 13 56 51" src="https://cloud.githubusercontent.com/assets/928964/23814746/89702b4e-0599-11e7-9ebb-2f6a17b392f2.png">

So I guess the real problem is that `terraform validate` is not catching errors like Yoz's.

**Comment by datn** [comment]
Okay, `tflint` doesn't understand Yoz's error either. Trying some other terraform linters.

**Comment by datn** [comment]
And furthermore, it doesn't seem like third-party linters are able to do the job. We need one of the following (both of which are hard):

* Hashicorp enhances `terraform validate` to dry-run everything that it does when it runs against the backend provider, as discussed in https://github.com/18F/dns/pull/71#issuecomment-286811395
* Concourse sends error output to the submitter of the PR 

Since we don't have any control over the second one, I'm going to look into Concourse options.

**Comment by datn** [comment]
https://github.com/18F/dns/pull/76
